mysql:
  # Process alarm threshold
  process-limit: 50
  # If credentals are not provided nor working, defaults to mysqld.sock and root user with no password
  credentials:
    user: "root"
    password: "password"
    host: "localhost"
    port: 3306
    dbname: "mysql"
    network: "tcp"
    socket: "/var/run/mysqld/mysqld.sock"
    allow-native-passwords: true
  auto-repair: # If enabled, monokit will run "mysqlcheck --auto-repair --all-databases" based on the weekly schedule.
    enabled: true
    day: "Sun" # Mon Tue Wed Thu Fri Sat Sun
    hour: "05:00" # 24h format, e.g. 05:00, 17:00
  pmm-agent:
    enabled: false
  alarm:
    enabled: true
  # Not implemented yet, can be added in the future versions
  cluster:
    enabled: false
    cluster_type: "" # ndb, xtradb
    size: 3
    receive-queue-limit: 10
    flow-control-limit: 0.20

mariadb:
  enabled: true
  process-limit: 50
  credentials:
    user: "root"
    password: "password"
    host: "localhost"
    port: 3306
    dbname: "mysql"
    network: "tcp"
    socket: "/var/run/mysqld/mysqld.sock"
    allow-native-passwords: true
  cluster:
    enabled: false
    cluster-type: "galera" # galera
    size: 3
    receive-queue-limit: 10
    flow-control-limit: 0.20
  auto-repair: # If enabled, monokit will run "mariadb-check --auto-repair --all-databases" based on the weekly schedule.
    enabled: true
    day: "Sun" # Mon Tue Wed Thu Fri Sat Sun
    hour: "05:00" # 24h format, e.g. 05:00, 17:00
  pmm-agent:
    enabled: false
  alarm:
    enabled: true

postgresql:
  process-limit: 50 # Process alarm threshold
  active-query-limit: 30 # Active queries at the same time
  connection-limit-percent: 70 # 70% of max_connections
  credentials:
    mode: "manual" # "manual" for host, port, user, password, dbname or "string" from connection-string
    connection-string: "postgres://postgres:1234@localhost:5432" # if mode is "string", this will be used to connect to the database
    # If mode is "manual", the following parameters will be used to connect to the database
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "1234"
    dbname: "postgres"
  long-query:
    enabled: true
    duration: 60 # In seconds
  pmm-agent:
    enabled: false
  alarm:
    enabled: true
  # Not implemented yet, can be added in the future versions
  cluster:
    enabled: false
    cluster-type: "patroni" # pgpool, patroni
    size: 3
    receive-queue-limit: 10
    flow-control-limit: 0.20
